name: 'Run Semodule Build on container'
description: 'Build SELinux modules on targeted OS'

inputs:
  os_target:
    description: 'Choose OS on which you want to build module '
    required: true
    default: 'titi'
#outputs:
#  modules: # id of output
#    description: 'The time we greeted you'

runs:
##  using: 'docker'
##  image: 'Dockerfile'
###  env:
###    OS_TARGET: ${{ inputs.os_target }}
##  args:
##    - ${{ inputs.os_target }}
  using: 'composite'
  steps:
    - uses: docker/build-push-action@v2
        with:
          context: ./
          push: false
          file: ./Dockerfile
          build-args: OS_TARGET=${{github.event.inputs.os_target}}
